// mine/day77-vue/day10-路由&vuex基本使用/my-vue/02-src-路由传参/views/Home/index.vue
<template>
  <div>
    <h2>Home</h2>
    <ul class="nav nav-tabs">
      <li><router-link to="/home/news">News</router-link></li>
      <li><router-link to="/home/message">Message</router-link></li>
    </ul>
    <router-view></router-view>
  </div>
</template>
<script>
export default {
  name: "Home",
};
</script>
<style>
</style>

// teacher/day67-react/day05-路由&Redux/上课资料/案例/src-router案例-改造前/pages/Home/index.js
import React, { Component } from 'react'
import Message from '../Message'
import News from '../News'

export default class Home extends Component {
  render() {
    return (
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className='nav nav-tabs'>
            <li>
              <a href='/home/news'>News</a>
            </li>
            <li>
              <a href='/home/message'>Message</a>
            </li>
          </ul>
          <div>
            <div>
              <News></News>
              <Message></Message>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
