// teacher/day77-vue/day10-路由&vuex基本使用/06.vue_router/src/views/Home/index.vue
<template>
  <div>
    <h3>home</h3>
    <ul class="nav nav-tabs">
      <li><router-link to="/home/news">News</router-link></li>
      <li><router-link to="/home/message">Message</router-link></li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Home",
  mounted() {
    console.log("Home mounted");
  },
  beforeDestroy() {
    console.log("Home beforeDestroy");
  },
  activated() {
    console.log("home activated");
  },
  deactivated() {
    console.log("home deactivated");
  },
};
</script>

<style>
</style>

// mine/day67-react/day05-路由&Redux/react/10-src-嵌套路由案例/pages/Home/index.js
import React, { Component } from 'react'
import Message from '../Message'
import News from '../News'
import { BrowserRouter as  Router,Link,Route} from 'react-router-dom'

export default class Home extends Component {
  render() {
    return (
      
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className='nav nav-tabs'>
            <li>
              {/* <a href='/home/news'>News</a> */}
              <Link to="/home/news">News</Link>
            </li>
            
              
            <li>
              {/* <a href='/home/message'>Message</a> */}
              <Link to="/home/message">Message</Link>
            </li>
          </ul>
          <div>
            <div>
              {/* <News></News>
              <Message></Message> */}
              {/* <Route path="/home/news" component={News}></Route> */}
                <Route path="/home/news" component={News}></Route>
                <Route path="/home/message" component={Message}></Route>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
