// mine/day67-react/day10-移动端项目/myapp/src/pages/Home/home.js
import React, { Component } from 'react'
import { Link } from "react-router-dom"
console.log("home加载了")
export default class Home extends Component {
    render() {
        return (
            <>
                <div>
                    home
            </div>
                <h1>
                    <Link to="/login">注册</Link>
                </h1>
            </>
        )
    }
}

// teacher/day77-vue/day10-路由&vuex基本使用/06.vue_router/src/views/Home/index.vue
<template>
  <div>
    <h3>home</h3>
    <ul class="nav nav-tabs">
      <li><router-link to="/home/news">News</router-link></li>
      <li><router-link to="/home/message">Message</router-link></li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Home",
  mounted() {
    console.log("Home mounted");
  },
  beforeDestroy() {
    console.log("Home beforeDestroy");
  },
  activated() {
    console.log("home activated");
  },
  deactivated() {
    console.log("home deactivated");
  },
};
</script>

<style>
</style>
