// mine/day77-vue/day09-插槽&vue-axios/my-vue/src/views/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchContent"
      />
      <button @click="handler">Search</button>
    </div>
  </section>
</template>
<script>
export default {
  name: "Search",
  data() {
    return {
      searchContent: "",
    };
  },
  methods: {
    handler() {
      this.$bus.$emit("getResult", this.searchContent);
    },
  },
};
</script>
<style>
</style>

// teacher/day67-react/day04-高阶组件&hooks/其他资料/src-users-静态页面/pages/Search/index.jsx
import React, { Component } from 'react'

export default class Search extends Component {
  render() {
    return (
      <section className='jumbotron'>
        <h3 className='jumbotron-heading'>Search Github Users</h3>
        <div>
          <input type='text' placeholder='enter the name you search' />
          <button>Search</button>
        </div>
      </section>
    )
  }
}
