// mine/day77-vue/day09-插槽&vue-axios/my-vue/src/views/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchContent"
      />
      <button @click="handler">Search</button>
    </div>
  </section>
</template>
<script>
export default {
  name: "Search",
  data() {
    return {
      searchContent: "",
    };
  },
  methods: {
    handler() {
      this.$bus.$emit("getResult", this.searchContent);
    },
  },
};
</script>
<style>
</style>

// mine/day67-react/day07-Redux&移动端/react/03-src-users案例过滤基本实现/pages/Search/index.jsx
import React, { Component } from 'react'

import PubSub from 'pubsub-js'
import { TOPIC } from '../../constans'
export default class Search extends Component {
  state = { searchName: '' }

  handleChange = e => {
    this.setState({
      searchName: e.target.value.trim()
    })
  }

  handleClick = () => {
    PubSub.publish(TOPIC, this.state.searchName)
  }
  render() {
    // console.log(this.props)
    return (
      <section className='jumbotron'>
        <h3 className='jumbotron-heading'>Search Github Users</h3>
        <div>
          <input
            type='text'
            placeholder='enter the name you search'
            value={this.state.searchName}
            onChange={this.handleChange}
          />
          <button onClick={this.handleClick}>Search</button>
        </div>
      </section>
    )
  }
}
